#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - git

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - git clone https://github.com/tbkiet22/to-do-microservices.git /app
  - cd /app
  - docker-compose up -d 